import { User, BriefcaseBusiness, FileText, Wallet } from 'lucide-react';
import { NotificationType } from '../providers/NotificationProvider';

export const STRINGS = {
  APP_NAME: 'connectHR',
  YEAR: 'Year - 2026',
  UPCOMING_HOLIDAYS: 'Upcoming Holidays',
  VIEW_ALL: 'View all',
  EMAIL_ADDRESS: 'Email Address',
  EMAIL_ADDRESS_PLACEHOLDER: 'Enter email address',
  PASSWORD: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter password',
  LOGIN: 'Login',
  PASSWORD_REQUIRED: 'Password is required',
  EMAIL_REQUIRED: 'Email address is required',
  EMAIL_INVALID: 'Please enter a valid email address',
  LOGIN_FAILED: 'Login Failed',
  WELCOME: 'Welcome',
  PLEASE_LOGIN_HERE: 'Please login here',
  PASSWORD_RESET_FAILED: 'Password Reset Failed',
  NEW_PASSWORD_REQUIRED: 'New password is required',
  NEW_PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
  CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  NEW_PASSWORD: 'New Password',
  ENTER_NEW_PASSWORD: 'Enter new password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CONFIRM_NEW_PASSWORD: 'Confirm new password',
  RESET_PASSWORD: 'Reset Password',
  PLEASE_CREATE_NEW_PASSWORD: 'Please create a new password.',
  PASSWORD_UPDATED_SUCCESSFULLY: 'Password updated successfully.',
  BACK_TO_LOGIN: 'Back to Login',
  PASSWORD_REQUIREMENT_MIN_LENGTH: 'At least 8 characters',
  PASSWORD_REQUIREMENT_UPPERCASE: 'One uppercase letter',
  PASSWORD_REQUIREMENT_LOWERCASE: 'One lowercase letter',
  PASSWORD_REQUIREMENT_NUMBER: 'One number',
  PASSWORD_REQUIREMENT_SPECIAL_CHARACTER: 'One special character',
  HOLIDAY_CREATION_FAILED: 'Holiday creation failed',
  HOLIDAY_CREATED_SUCCESSFULLY: 'Holiday created successfully',
  HOLIDAY_DELETION_FAILED: 'Holiday deletion failed',
  HOLIDAY_DELETED_SUCCESSFULLY: 'Holiday deleted successfully',
  ADD_NEW_HOLIDAY: 'Add New Holiday',
  HOLIDAYS: 'Holidays',
  ALL_HOLIDAY_LISTS: 'All Holiday Lists',
  HOLIDAY_NAME_IS_REQUIRED: 'Holiday name is required',
  HOLIDAY_DATE_IS_REQUIRED: 'Holiday date is required',
  HOLIDAY_NAME: 'Holiday Name',
  HOLIDAY_NAME_PLACEHOLDER: 'Enter Holiday Name',
  SELECT_DATE: 'Select Date',
  CANCEL: 'Cancel',
  ADD: 'Add',
  EXPORT: 'Export',
  DOWNLOAD: 'Download',
  EXPORT_HOLIDAYS_CONFIRMATION: 'The holiday list will be downloaded as an Excel file. Do you want to continue?',
  HOLIDAYS_EXPORTED_SUCCESSFULLY: 'Holidays exported successfully',
  HOLIDAYS_EXPORT_FAILED: 'Holidays export failed',
  EXPORT_EMPLOYEES_CONFIRMATION: 'The employee list will be downloaded as an Excel file. Choose what to include:',
  EXPORT_SCOPE_LABEL: 'What to export',
  EXPORT_SCOPE_ALL: 'All records',
  EXPORT_SCOPE_FILTERED: 'Only the list currently shown',
  EXPORT_SCOPE_ALL_EMPLOYEES: 'All employees',
  EMPLOYEES_EXPORTED_SUCCESSFULLY: 'Employees exported successfully',
  EMPLOYEES_EXPORT_FAILED: 'Employees export failed',
  NO_HOLIDAYS_ADDED: 'No holidays added yet',
  NO_DATA_FOUND: 'No data found',
  SHOWING: 'Showing',
  EMPLOYEES_FETCH_FAILED: 'Failed to load employees',
  FILTER: 'Filter',
  APPLY_FILTER: 'Apply Filter',
  CLEAR: 'Clear',
  ALL_EMPLOYEES: 'All Employees',
  ALL_EMPLOYEE_INFORMATION: 'All Employee Information',
  ADD_NEW_EMPLOYEE: 'Add New Employee',
  EDIT_EMPLOYEE: 'Edit Employee',
  SEARCH_EMPLOYEE: 'Search employee...',
  CREATE_EMPLOYEE: 'Create Employee',
  UPDATE_EMPLOYEE: 'Update Employee',
  EMPLOYEE_CREATED_SUCCESSFULLY: 'Employee created successfully',
  EMPLOYEE_CREATION_FAILED: 'Employee creation failed',
  EMPLOYEE_UPDATE_FAILED: 'Employee update failed',
  NO_CHANGES_TO_UPDATE: 'No changes to update',
  NOTHING_WAS_CHANGED: 'Edit a field before saving, or go back to the employee.',
  EMPLOYEE_ID: 'Employee ID',
  DEPARTMENT: 'Department',
  DESIGNATION: 'Designation',
  EMPLOYEE_TYPE: 'Employee Type',
  EMPLOYMENT_STATUS: 'Employment Status',
  BACK_TO_ALL_EMPLOYEES: 'Back to All Employees',
  EMPLOYEE_FETCH_FAILED: 'Failed to load employee',
  EDIT_PROFILE: 'Edit Profile',
  PROFILE: 'Profile',
  SEPARATION: 'Separation',
  NO_DOCUMENTS_UPLOADED: 'No documents uploaded yet',
  NOT_AVAILABLE: '--',
  TOTAL_EMPLOYEE: 'Total Employee',
  TODAY_ATTENDANCE: 'Today Attendance',
  TODAY_ON_LEAVE: 'Today On Leave',
  DEPARTMENT_DISTRIBUTION: 'Department Distribution',
  EMPLOYEES: 'Employees',
  NO_UPCOMING_HOLIDAYS: 'No upcoming holidays',
  LOGOUT: 'Logout',
  SESSION_EXPIRED: 'Your session has expired due to inactivity. Please log in again.',
  ACCOUNT_MENU: 'Account menu',
  CREATE_USER: 'Create User',
  ADD_NEW_USER: 'Add New User',
  USERS: 'Users',
  ALL_USER_ACCOUNTS: 'All user accounts',
  USER_NAME: 'Name',
  USER_EMAIL: 'Email',
  USER_ROLE: 'Role',
  USER_STATUS: 'Status',
  USER_LAST_LOGIN: 'Last Login',
  USER_CREATED_BY: 'Created By',
  NEVER: 'Never',
  USERS_FETCH_FAILED: 'Failed to load users',
  FULL_NAME: 'Full Name',
  FULL_NAME_PLACEHOLDER: 'Enter full name',
  NAME_REQUIRED: 'Name is required',
  ROLE_REQUIRED: 'Role is required',
  SELECT_ROLE: 'Select a role',
  ROLES_FETCH_FAILED: 'Failed to load assignable roles',
  NO_ASSIGNABLE_ROLES: 'Your account cannot assign any roles.',
  USER_CREATED_SUCCESSFULLY: 'User created successfully',
  USER_CREATION_FAILED: 'User creation failed',
  EMAIL_ALREADY_EXISTS: 'An account with this email already exists',
  TEMPORARY_PASSWORD: 'Temporary Password',
  TEMPORARY_PASSWORD_WARNING:
    'This password is shown once and cannot be retrieved again. Copy it now and share it with the user securely.',
  COPY: 'Copy',
  COPIED: 'Copied',
  COPY_FAILED: 'Could not copy — select the password and copy it manually.',
  CREATE_ANOTHER_USER: 'Create Another User',
  BACK_TO_USERS: 'Back to Users',
  CREATE: 'Create',
};

export const STEPS = [
  {
    id: 'personal-information',
    label: 'Personal Information',
    icon: User,
  },
  {
    id: 'professional-information',
    label: 'Professional Information',
    icon: BriefcaseBusiness,
  },
  {
    id: 'payroll-information',
    label: 'Payroll Information',
    icon: Wallet,
  },
  {
    id: 'documents',
    label: 'Documents',
    icon: FileText,
  },
] as const;

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  EMPLOYEES: '/employees',
  HOLIDAYS: '/holidays',
  USERS: '/users',
  CREATE_USER: '/create-user',
} as const;

/**
 * Marks a login redirect issued by a server render that found the session
 * unusable. `proxy.ts` gates only on the presence of the access-token cookie,
 * which such a render cannot always clear — cookies are only writable from a
 * Server Action or Route Handler, not mid-render. Without this marker the
 * proxy would see the stale cookie, bounce the request back to the dashboard,
 * and the two would redirect at each other indefinitely.
 */
export const SESSION_EXPIRED_QUERY = {
  KEY: 'session',
  VALUE: 'expired',
} as const;

export const LOGIN_SESSION_EXPIRED_URL = `${ROUTES.LOGIN}?${SESSION_EXPIRED_QUERY.KEY}=${SESSION_EXPIRED_QUERY.VALUE}`;

/**
 * How a Route Handler tells the browser that the 401 it just returned was an
 * idle timeout rather than an ordinary authorization failure — the first calls
 * for a trip to the login screen, the second for an error message in place.
 */
export const SESSION_EXPIRED_CODE = 'SESSION_EXPIRED';

export const NOTIFICATION_TYPES: Record<string, NotificationType> = {
  SUCCESS: 'success',
  ERROR: 'error',
  WARNING: 'warning',
  INFO: 'info',
};
