export interface PersonalInformation {
  firstName: string;
  lastName: string;
  mobileNumber: string;
  email: string;
  dateOfBirth: string;
  gender: string;
  nationality: string;
  maritalStatus: string;
  aadhaarNumber: string;
  currentAddress: string;
  currentCity: string;
  /**
   * Both address lookups are stored by code, not by name: the state's `code` from
   * `/locations/states` — which is also what the districts lookup is keyed on — and the
   * district's `code` from that state's districts.
   */
  currentState: string;
  currentDistrictCode: string;
  currentPinCode: string;
  sameAsCurrentAddress: boolean;
  permanentAddress: string;
  permanentCity: string;
  permanentState: string;
  permanentDistrictCode: string;
  permanentPinCode: string;
  emergencyContactName: string;
  emergencyRelationship: string;
  emergencyPhoneNumber: string;
  emergencyAddress: string;
}

/**
 * No `employeeID`: the identifier is generated by the backend ("EMP" plus the next number in
 * the series) and returned on the response. The create endpoint rejects a payload that sends
 * one, so the read-only field the wizard displays is deliberately not part of this shape.
 */
export interface ProfessionalInformation {
  employeeType: string;
  employmentStatus: string;
  dateOfJoining: string;
  department: string;
}

export interface PayrollInformation {
  accountHolderName: string;
  bankName: string;
  accountNumber: string;
  confirmAccountNumber: string;
  ifscCode: string;
  branchName: string;
  panNumber: string;
  uanNumber: string;
  esicNumber: string;
}

/**
 * The wizard collects exactly the shape the backend expects, one step per key, so the
 * employee store doubles as the request body and no assembly step is needed at submit.
 */
export interface CreateEmployeeRequest {
  personalInformation: PersonalInformation;
  professionalInformation: ProfessionalInformation;
  payrollInformation: PayrollInformation;
}

/**
 * The record the backend echoes back on creation. Deliberately not the list `Employee`:
 * that one flattens these to `type`/`status`, and the two shapes are free to diverge.
 */
export interface CreatedEmployee {
  id: string;
  avatar: string;
  name: string;
  employeeId: string;
  department: string;
  designation: string;
  employeeType: string;
  employmentStatus: string;
}

export interface CreateEmployeeResponse {
  success: boolean;
  message: string;
  data: CreatedEmployee;
}

/**
 * Mirrors `GetEmployeesResult` — a plain, serializable outcome, since a Server Function
 * cannot carry `ApiError` across the client/server boundary intact.
 */
export type CreateEmployeeResult =
  | { success: true; message: string; data: CreatedEmployee }
  | { success: false; message: string };

export interface Employee {
  id: string;
  avatar: string;
  name: string;
  employeeId: string;
  department: string;
  designation: string;
  type: string;
  status: string;
}

export interface EmployeeColumn {
  accessorKey: string;
  header: string;
}

export interface GetEmployeeColumnsResponse {
  success: boolean;
  message: string;
  data: EmployeeColumn[];
}

export interface EmployeeFilter {
  /**
   * The filter group's `id` from `/filters/employee`.
   */
  key: string;

  /**
   * Every selected option value for that group — the backend ORs them.
   */
  values: string[];
}

export type EmployeeSortOrder = 'asc' | 'desc';

export interface GetEmployeesRequest {
  page: number;
  limit: number;
  search?: string;
  filters?: EmployeeFilter[];
  sortBy?: string;
  sortOrder?: EmployeeSortOrder;
}

export interface EmployeeListMeta {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

export interface GetEmployeesResponse {
  success: boolean;
  message: string;
  data: Employee[];
  meta: EmployeeListMeta;
}

/**
 * Server Functions can't let custom error classes (e.g. `ApiError`) cross
 * the client/server boundary intact, so `getEmployees` reports failure
 * through this plain, serializable result instead of throwing.
 */
export type GetEmployeesResult =
  | { success: true; data: Employee[]; meta: EmployeeListMeta }
  | { success: false; message: string };
