export interface PersonalInformation {
  firstName: string;
  lastName: string;
  mobileNumber: string;
  email: string;
  dateOfBirth: string;
  gender: string;
  nationality: string;
  maritalStatus: string;
  aadhaarNumber: string;
  currentAddress: string;
  currentCity: string;
  /**
   * Both address lookups are stored by code, not by name: the state's `code` from
   * `/locations/states` — which is also what the districts lookup is keyed on — and the
   * district's `code` from that state's districts.
   */
  currentState: string;
  currentDistrictCode: string;
  currentPinCode: string;
  sameAsCurrentAddress: boolean;
  permanentAddress: string;
  permanentCity: string;
  permanentState: string;
  permanentDistrictCode: string;
  permanentPinCode: string;
  emergencyContactName: string;
  emergencyRelationship: string;
  emergencyPhoneNumber: string;
  emergencyAddress: string;
}

/**
 * No `employeeID`: the identifier is generated by the backend ("EMP" plus the next number in
 * the series) and returned on the response. The create endpoint rejects a payload that sends
 * one, so the read-only field the wizard displays is deliberately not part of this shape.
 */
export interface ProfessionalInformation {
  employeeType: string;
  employmentStatus: string;
  dateOfJoining: string;
  department: string;
}

export interface PayrollInformation {
  accountHolderName: string;
  bankName: string;
  accountNumber: string;
  confirmAccountNumber: string;
  ifscCode: string;
  branchName: string;
  panNumber: string;
  uanNumber: string;
  esicNumber: string;
}

/**
 * The wizard collects exactly the shape the backend expects, one step per key, so the
 * employee store doubles as the request body and no assembly step is needed at submit.
 */
export interface CreateEmployeeRequest {
  personalInformation: PersonalInformation;
  professionalInformation: ProfessionalInformation;
  payrollInformation: PayrollInformation;
}

/**
 * The handful of fields the wizard's confirmation modal lists back. Both the create and the
 * update response carry them, in different shapes, so the modal is written against this and
 * each response is mapped onto it.
 */
export interface EmployeeSummary {
  name: string;
  employeeId: string;
  department: string;
  designation: string;
  employeeType: string;
  employmentStatus: string;
}

/**
 * The record the backend echoes back on creation. Deliberately not the list `Employee`:
 * that one flattens these to `type`/`status`, and the two shapes are free to diverge.
 */
export interface CreatedEmployee extends EmployeeSummary {
  id: string;
  avatar: string;
}

export interface CreateEmployeeResponse {
  success: boolean;
  message: string;
  data: CreatedEmployee;
}

/**
 * Mirrors `GetEmployeesResult` — a plain, serializable outcome, since a Server Function
 * cannot carry `ApiError` across the client/server boundary intact.
 */
export type CreateEmployeeResult =
  | { success: true; message: string; data: CreatedEmployee }
  | { success: false; message: string };

export interface Employee {
  id: string;
  avatar: string;
  name: string;
  employeeId: string;
  department: string;
  designation: string;
  type: string;
  status: string;
}

/**
 * What `/employees/:id` returns for the address lookups. Unlike the create payload it
 * carries the resolved district *names* alongside the codes, so the details screen can
 * render them without a second round trip to `/locations`.
 */
export interface EmployeePersonalDetails extends Omit<PersonalInformation, 'sameAsCurrentAddress'> {
  currentDistrict: string;
  permanentDistrict: string;
}

/**
 * The read model is richer than the create payload: `designation` and `workMode` are
 * derived by the backend and only ever come back on a read.
 */
export interface EmployeeProfessionalDetails extends ProfessionalInformation {
  designation: string;
  workMode: string;
}

/**
 * `confirmAccountNumber` only exists to validate the form — it is never stored, so it
 * never comes back.
 */
export type EmployeePayrollDetails = Omit<PayrollInformation, 'confirmAccountNumber'>;

/**
 * A single employee's full record, as returned by `/employees/:id`. Kept separate from the
 * flat list `Employee`: that one is shaped for table columns, this one for the details screen.
 */
export interface EmployeeDetail {
  id: string;
  employeeId: string;
  avatar: string;
  name: string;
  personalInformation: EmployeePersonalDetails;
  professionalInformation: EmployeeProfessionalDetails;
  payrollInformation: EmployeePayrollDetails;
  createdAt: string;
  updatedAt: string;
}

export interface GetEmployeeResponse {
  success: boolean;
  message: string;
  data: EmployeeDetail;
}

/**
 * The PATCH payload for `/employees/:id`. Every section is optional, and so is every field
 * inside it: only what the user actually changed is sent, so an untouched section never
 * reaches the backend at all.
 *
 * The fields the wizard carries purely for the UI — the "same as current address" toggle,
 * the confirm-account-number field, and the read-only Employee ID — are not part of this
 * shape; `toUpdateEmployeeRequest` is what leaves them out.
 */
export interface UpdateEmployeeRequest {
  personalInformation?: Partial<Omit<PersonalInformation, 'sameAsCurrentAddress'>>;
  professionalInformation?: Partial<EmployeeProfessionalDetails>;
  payrollInformation?: Partial<EmployeePayrollDetails>;
}

/**
 * Unlike create, the update endpoint echoes back the *full* record — the same shape
 * `/employees/:id` returns.
 */
export interface UpdateEmployeeResponse {
  success: boolean;
  message: string;
  data: EmployeeDetail;
}

/**
 * Mirrors `CreateEmployeeResult` — a plain, serializable outcome, since a Server Function
 * cannot carry `ApiError` across the client/server boundary intact.
 */
export type UpdateEmployeeResult =
  | { success: true; message: string; data: EmployeeDetail }
  | { success: false; message: string };

export interface EmployeeColumn {
  accessorKey: string;
  header: string;
}

export interface GetEmployeeColumnsResponse {
  success: boolean;
  message: string;
  data: EmployeeColumn[];
}

export interface EmployeeFilter {
  /**
   * The filter group's `id` from `/filters/employee`.
   */
  key: string;

  /**
   * Every selected option value for that group — the backend ORs them.
   */
  values: string[];
}

export type EmployeeSortOrder = 'asc' | 'desc';

export interface GetEmployeesRequest {
  page: number;
  limit: number;
  search?: string;
  filters?: EmployeeFilter[];
  sortBy?: string;
  sortOrder?: EmployeeSortOrder;
}

export interface EmployeeListMeta {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

export interface GetEmployeesResponse {
  success: boolean;
  message: string;
  data: Employee[];
  meta: EmployeeListMeta;
}

/**
 * Server Functions can't let custom error classes (e.g. `ApiError`) cross
 * the client/server boundary intact, so `getEmployees` reports failure
 * through this plain, serializable result instead of throwing.
 */
export type GetEmployeesResult =
  | { success: true; data: Employee[]; meta: EmployeeListMeta }
  | { success: false; message: string };
